name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Count CPUs
        id: count-cpus
        run: |
          echo "CPUS: $(nproc)"

      - name: Build
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          target: export
          platforms: linux/amd64
          # platforms: linux/amd64,linux/arm64
          outputs: type=local,dest=./output

      - name: List files
        id: list-files
        run: find ./output -type f

      # TODO - test files

      # TODO - draft release
      # - name: Draft release
      #   id: draft-release
      #   if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
      #   with:
      #     draft: true
      #     files: output/build/*
      #     fail_on_unmatched_files: true

