name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    tags: [v*]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (amd64)
        if: matrix.os == 'ubuntu-24.04'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          target: export
          platforms: linux/amd64
          outputs: type=local,dest=./output

      - name: Build (arm64)
        if: matrix.os == 'ubuntu-24.04-arm'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          target: export
          platforms: linux/arm64
          outputs: type=local,dest=./output

      - name: List files
        run: find ./output -type f

      # TODO - test files

      # TODO - draft release
      # - name: Draft release
      #   if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
      #   with:
      #     draft: true
      #     files: output/build/*
      #     fail_on_unmatched_files: true

